### ISSUE TITLE
Action fails with installing boost python libs in windows-latest runner

### ISSUE THREAD

**Issue by mpconte** [egor-tensin/build-boost#6]
Github action:

```
      - name: Build Boost        
        uses: egor-tensin/build-boost@v1
        id: boost
        with:
          version: 1.73.0
          toolset: msvc142
          libraries: atomic chrono context coroutine container date_time exception filesystem graph graph_parallel iostreams locale log math mpi program_options python random regex serialization signals system test thread timer wave

```

Produces the following error:

```
2022-03-22 18:09:55 | INFO | Trying URL: https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.gz
2022-03-22 18:10:00 | INFO | Writing Boost archive: D:\a\hyprdsp\boost_1_73_0.tar.gz
2022-03-22 18:10:00 | INFO | Unpacking Boost to: D:\a\hyprdsp\boost_1_73_0
2022-03-22 18:10:41 | INFO | Running executable: ['.\\bootstrap.bat']
Building Boost.Build engine

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

2022-03-22 18:10:42 | ERROR | Command '['.\\bootstrap.bat']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\project\utils.py", line 64, in setup_logging
    yield
  File "C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\project\boost\build.py", line 202, in _main
    build(BuildParameters.from_cmd_args(args))
  File "C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\project\boost\build.py", line 138, in build
    boost_dir.build(params)
  File "C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\project\boost\directory.py", line 25, in build
    self._bootstrap_if_required(params)
  File "C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\project\boost\directory.py", line 32, in _bootstrap_if_required
    self.bootstrap(params)
  File "C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\project\boost\directory.py", line 36, in bootstrap
    run([self._bootstrap_path()] + self._bootstrap_args(params.toolset_version))
  File "C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\project\utils.py", line 82, in run
    return subprocess.run(cmd_line, check=True, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.10\x64\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['.\\bootstrap.bat']' returned non-zero exit status 1.
```

under the **windows-latest** github runner

**Comment by egor-tensin** [comment]
Assuming no longer relevant; cleaning up issues I've neglected.
